// Generated by Copilot
export interface GridConfig {
    readonly minWidth: number;
    readonly maxWidth: number;
    readonly minHeight: number;
    readonly maxHeight: number;
}

export const defaultGridConfig: GridConfig = {
    minWidth: 3,
    maxWidth: 12,
    minHeight: 3,
    maxHeight: 12
};