<!-- Generated by Copilot -->
<script lang="ts">
    import type { Grid } from '../models/Grid';
    import type { Tile } from '../models/Tile';

    export let grid: Grid;
    
    // Compute cell size based on viewport
    $: cellSize = Math.min(
        Math.floor(window.innerWidth * 0.8 / grid.dimensions[0]), // 80% of viewport width
        Math.floor(window.innerHeight * 0.8 / grid.dimensions[1])  // 80% of viewport height
    );
</script>

<div class="game-grid" role="grid" aria-label="Game Grid"
    style:--grid-columns={grid.dimensions[0]}
    style:--grid-rows={grid.dimensions[1]}
    style:--cell-size="{cellSize}px">
    {#each grid.tiles as row, rowIndex}
        {#each row as tile, colIndex}
            <div class="cell" role="gridcell"
                data-row={rowIndex}
                data-col={colIndex}>
                {#if tile}
                    <span class="tile-value">{tile.value}</span>
                {/if}
            </div>
        {/each}
    {/each}
</div>

<style>
    .game-grid {
        display: grid;
        grid-template-columns: repeat(var(--grid-columns), var(--cell-size));
        grid-template-rows: repeat(var(--grid-rows), var(--cell-size));
        gap: 2px;
        padding: 2px;
        background-color: #333;
        border-radius: 8px;
        margin: 0 auto;
    }

    .cell {
        background-color: #222;
        border-radius: 4px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: calc(var(--cell-size) * 0.5);
        font-weight: bold;
        color: #fff;
        user-select: none;
        transition: background-color 0.2s ease;
    }

    .cell:hover {
        background-color: #2a2a2a;
    }

    .tile-value {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 90%;
        height: 90%;
        background-color: #646cff;
        border-radius: 4px;
        transition: transform 0.2s ease;
    }

    .tile-value:hover {
        transform: scale(1.05);
    }

    @media (prefers-color-scheme: light) {
        .game-grid {
            background-color: #e0e0e0;
        }

        .cell {
            background-color: #f5f5f5;
            color: #213547;
        }

        .cell:hover {
            background-color: #eaeaea;
        }

        .tile-value {
            background-color: #535bf2;
            color: #fff;
        }
    }

    @media (max-width: 768px) {
        .game-grid {
            gap: 1px;
            padding: 1px;
        }
    }
</style>