<!-- Generated by Copilot -->
<script lang="ts">
    import { loadGridConfig } from '../config/configLoader';
    import type { Grid } from '../models/Grid';
    import { createEventDispatcher } from 'svelte';
    
    const dispatch = createEventDispatcher<{
        startGame: { width: number; height: number; }
    }>();
    
    const config = loadGridConfig();
    
    let width = 5;
    let height = 5;
    let error = '';
    
    function validateDimensions(): boolean {
        if (width < config.minWidth || width > config.maxWidth) {
            error = `Width must be between ${config.minWidth} and ${config.maxWidth}`;
            return false;
        }
        if (height < config.minHeight || height > config.maxHeight) {
            error = `Height must be between ${config.minHeight} and ${config.maxHeight}`;
            return false;
        }
        error = '';
        return true;
    }
    
    function handleStartGame() {
        if (validateDimensions()) {
            dispatch('startGame', { width, height });
        }
    }
</script>

<div class="settings-modal" role="dialog" aria-labelledby="settings-title">
    <div class="modal-content">
        <h2 id="settings-title">Game Settings</h2>
        
        <section class="grid-setup" role="form" aria-label="Grid size selection">
            <div class="input-group">
                <label for="width">Width:</label>
                <input 
                    type="number" 
                    id="width" 
                    bind:value={width} 
                    min={config.minWidth} 
                    max={config.maxWidth}
                    aria-describedby="width-constraints"
                />
                <span id="width-constraints" class="constraints">
                    ({config.minWidth}-{config.maxWidth})
                </span>
            </div>
            
            <div class="input-group">
                <label for="height">Height:</label>
                <input 
                    type="number" 
                    id="height" 
                    bind:value={height} 
                    min={config.minHeight} 
                    max={config.maxHeight}
                    aria-describedby="height-constraints"
                />
                <span id="height-constraints" class="constraints">
                    ({config.minHeight}-{config.maxHeight})
                </span>
            </div>
        </section>
        
        {#if error}
            <div class="error" role="alert">
                {error}
            </div>
        {/if}
        
        <button 
            class="start-button"
            on:click={handleStartGame}
            aria-disabled={!validateDimensions()}
        >
            Start Game
        </button>
    </div>
</div>

<style>
    .settings-modal {
        position: fixed;
        inset: 0;
        display: grid;
        place-items: center;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 1000;
    }

    .modal-content {
        background-color: var(--color-background-alt);
        padding: 2rem;
        border-radius: 1rem;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        max-width: 90vw;
        width: max-content;
    }

    h2 {
        color: #646cff;
        margin-top: 0;
        margin-bottom: 1.5rem;
        text-align: center;
    }

    .grid-setup {
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }

    .input-group {
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }

    label {
        min-width: 4rem;
        text-align: right;
    }

    input {
        width: 5rem;
        padding: 0.5rem;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 1rem;
    }

    .constraints {
        color: #666;
        font-size: 0.875rem;
    }

    .start-button {
        width: 100%;
        margin-top: 1.5rem;
        padding: 0.8em 1.5em;
        background-color: #646cff;
        color: white;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        font-weight: 500;
        transition: all 0.2s ease;
    }

    .start-button:hover:not([aria-disabled="true"]) {
        background-color: #535bf2;
        transform: translateY(-1px);
    }

    .start-button[aria-disabled="true"] {
        background-color: #cccccc;
        cursor: not-allowed;
    }

    .error {
        color: #ef4444;
        padding: 0.5rem;
        margin-top: 1rem;
        border: 1px solid currentColor;
        border-radius: 4px;
        text-align: center;
    }

    @media (prefers-color-scheme: light) {
        .modal-content {
            background-color: #f5f5f5;
        }

        h2 {
            color: #535bf2;
        }
    }

    :root {
        --color-background-alt: #2a2a2a;
    }

    @media (max-width: 480px) {
        .modal-content {
            padding: 1.5rem;
        }

        .input-group {
            flex-direction: column;
            align-items: stretch;
        }

        label {
            text-align: left;
        }

        input {
            width: 100%;
        }
    }
</style>